var { faker }  = require("@faker-js/faker")

var admin = require("firebase-admin");

var serviceAccount = require("./server-accountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();
function setRequest() {
  [...Array(5)].map((item) =>
    db.collection("member_request").add({
      first_name: faker.person.firstName(),
      last_name: faker.person.lastName(),
      gender: "Male",
      email: faker.internet.email(),
      phone: faker.phone.number(),
      university: "Moscow State University",
      title:"Mr",
      graduationDate:"2000-08-07",
      occupation:"Econmist",
      commencementDate: "1995-08-07",
      country: "Russia",
      qualification: "undergraduate",
      major: "Economics",
      requestedAt: admin.firestore.FieldValue.serverTimestamp(),
      sector: "public",
      orgName: "Ministry of Economics and Finance",
      business: [
        {
          name: faker.company.name(),
          type:"Banking",
          email: faker.internet.email(),
          phone: faker.phone.number(),
          description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
          position: "Managing Director",
          address: faker.location.streetAddress(),
        },
      ],
      businessTypes:["Banking"],
      dateOfBirth: "1975-08-07",
      requestStatus: "new",
    }).then().catch((e)=> console.log(e))
  );
}
setRequest();

function setData() {
  [...Array(5)].map((item) =>
    db.collection("members").add({
      first_name: faker.person.firstName(),
      last_name: faker.person.lastName(),
      gender: "Male",
      email: faker.internet.email(),
      phone: faker.phone.number(),
      university: "Moscow State University",
      title:"Mr",
      graduationDate:"2000-08-07",
      occupation:"Econmist",
      commencementDate: "1995-08-07",
      country: "Russia",
      qualification: "undergraduate",
      major: "Economics",
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      sector: "public",
      sector: "",
      orgName: "Ministry of Economics and Finance",
      business: [
        {
          name: faker.company.name(),
          type:"Banking",
          email: faker.internet.email(),
          phone: faker.phone.number(),
          description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
          position: "Managing Director",
          address: faker.location.streetAddress(),
        },
      ],
      businessTypes:["Banking"],
      dateOfBirth: "1975-08-07",
      status: "validated",
    }).then().catch((e)=> console.log(e))
  );
}



function setConst () {
    db.doc("constants/industryType").set(({
        values:
[
  "General Agriculture",
  "Agriculture Production And Management",
  "Agricultural Economics",
  "Animal Sciences",
  "Food Science",
  "Plant Science And Agronomy",
  "Soil Science",
  "Miscellaneous Agriculture",
  "Forestry",
  "Natural Resources Management",
  "Fine Arts",
  "Drama And Theater Arts",
  "Music",
  "Visual And Performing Arts",
  "Commercial Art And Graphic Design",
  "Film Video And Photographic Arts",
  "Studio Arts",
  "Miscellaneous Fine Arts",
  "Environmental Science",
  "Biology",
  "Biochemical Sciences",
  "Botany",
  "Molecular Biology",
  "Ecology",
  "Genetics",
  "Microbiology",
  "Pharmacology",
  "Physiology",
  "Zoology",
  "Neuroscience",
  "Miscellaneous Biology",
  "Cognitive Science And Biopsychology",
  "General Business",
  "Accounting",
  "Actuarial Science",
  "Business Management And Administration",
  "Operations Logistics And E-commerce",
  "Business Economics",
  "Marketing And Marketing Research",
  "Finance",
  "Human Resources And Personnel Management",
  "International Business",
  "Hospitality Management",
  "Management Information Systems And Statistics",
  "Miscellaneous Business & Medical Administration",
  "Communications",
  "Journalism",
  "Mass Media",
  "Advertising And Public Relations",
  "Communication Technologies",
  "Computer And Information Systems",
  "Computer Programming And Data Processing",
  "Computer Science",
  "Information Sciences",
  "Computer Administration Management And Security",
  "Computer Networking And Telecommunications",
  "Mathematics",
  "Applied Mathematics",
  "Statistics And Decision Science",
  "Mathematics And Computer Science",
  "General Education",
  "Educational Administration And Supervision",
  "School Student Counseling",
  "Elementary Education",
  "Mathematics Teacher Education",
  "Physical And Health Education Teaching",
  "Early Childhood Education",
  "Science And Computer Teacher Education",
  "Secondary Teacher Education",
  "Special Needs Education",
  "Social Science Or History Teacher Education",
  "Teacher Education: Multiple Levels",
  "Language And Drama Education",
  "Art And Music Education",
  "Miscellaneous Education",
  "Library Science",
  "Architecture",
  "General Engineering",
  "Aerospace Engineering",
  "Biological Engineering",
  "Architectural Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Engineering Mechanics Physics And Science",
  "Environmental Engineering",
  "Geological And Geophysical Engineering",
  "Industrial And Manufacturing Engineering",
  "Materials Engineering And Materials Science",
  "Mechanical Engineering",
  "Metallurgical Engineering",
  "Mining And Mineral Engineering",
  "Naval Architecture And Marine Engineering",
  "Nuclear Engineering",
  "Petroleum Engineering",
  "Miscellaneous Engineering",
  "Engineering Technologies",
  "Engineering And Industrial Management",
  "Electrical Engineering Technology",
  "Industrial Production Technologies",
  "Mechanical Engineering Related Technologies",
  "Miscellaneous Engineering Technologies",
  "Materials Science",
  "Nutrition Sciences",
  "General Medical And Health Services",
  "Communication Disorders Sciences And Services",
  "Health And Medical Administrative Services",
  "Medical Assisting Services",
  "Medical Technologies Technicians",
  "Health And Medical Preparatory Programs",
  "Nursing",
  "Pharmacy Pharmaceutical Sciences And Administration",
  "Treatment Therapy Professions",
  "Community And Public Health",
  "Miscellaneous Health Medical Professions",
  "Area Ethnic And Civilization Studies",
  "Linguistics And Comparative Language And Literature",
  "French German Latin And Other Common Foreign Language Studies",
  "Other Foreign Languages",
  "English Language And Literature",
  "Composition And Rhetoric",
  "Liberal Arts",
  "Humanities",
  "Intercultural And International Studies",
  "Philosophy And Religious Studies",
  "Theology And Religious Vocations",
  "Anthropology And Archeology",
  "Art History And Criticism",
  "History",
  "United States History",
  "Cosmetology Services And Culinary Arts",
  "Family And Consumer Sciences",
  "Military Technologies",
  "Physical Fitness Parks Recreation And Leisure",
  "Construction Services",
  '"Electrical, Mechanical, And Precision Technologies And Production"',
  "Transportation Sciences And Technologies",
  "Multi/interdisciplinary Studies",
  "Court Reporting",
  "Pre-law And Legal Studies",
  "Criminal Justice And Fire Protection",
  "Public Administration",
  "Public Policy",
  "N/a (Less Than Bachelor's Degree)",
  "Physical Sciences",
  "Astronomy And Astrophysics",
  "Atmospheric Sciences And Meteorology",
  "Chemistry",
  "Geology And Earth Science",
  "Geosciences",
  "Oceanography",
  "Physics",
  "Multi-disciplinary Or General Science",
  '"Nuclear, Industrial Radiology, And Biological Technologies"',
  "Psychology",
  "Educational Psychology",
  "Clinical Psychology",
  "Counseling Psychology",
  "Industrial And Organizational Psychology",
  "Social Psychology",
  "Miscellaneous Psychology",
  "Human Services And Community Organization",
  "Social Work",
  "Interdisciplinary Social Sciences",
  "General Social Sciences",
  "Economics",
  "Criminology",
  "Geography",
  "International Relations",
  "Political Science And Government",
  "Sociology",
  "Miscellaneous Social Sciences",
]
    })).then().catch(e => console.log(e));
}

